// OpenCode plugin and Hermes shell-hook installation.
//
// Kept out of hooks.rs on purpose: that file is entirely about Claude Code's
// settings.json, and the merge rules here are different (a JS file we own outright,
// and a YAML block we own between markers). Same preview/backup/confirm discipline.

use std::path::{Path, PathBuf};

use serde::Serialize;

use crate::{hooks, platform};

/// Identifies a file Coucou generated, and is checked before deleting anything.
pub const OPENCODE_MARKER: &str = "generated by Coucou";

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentStatus {
    pub installed: bool,
    pub path: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentPreview {
    pub diff: String,
    pub backup: String,
    pub path: String,
    /// The bytes this diff was computed from; handed back to `write` so we only
    /// ever apply what the user actually looked at.
    pub fingerprint: String,
}

pub fn opencode_plugin_path() -> PathBuf {
    // XDG-style on every platform, which is what OpenCode itself uses — that is
    // why OpenCode works on Windows and Amp does not.
    platform::home_dir().join(".config/opencode/plugins/coucou.js")
}

fn is_ours(text: &str) -> bool {
    text.contains(OPENCODE_MARKER)
}

/// The generated plugin, with the relay path substituted in.
///
/// ponytail: the same JavaScript exists as a Swift string literal in HookServer.swift
/// for the macOS app. Two copies because the two apps are separate binaries; both
/// sides assert the same tokens in their own test, so a drift shows up as a failure
/// rather than as a silently broken agent.
pub fn opencode_plugin_source(hook_exe: &str) -> String {
    // Backslashes would start an escape inside the JS single-quoted literal.
    let hook = hook_exe.replace('\\', "\\\\").replace('\'', "\\'");
    OPENCODE_PLUGIN_JS.replace("__HOOK__", &hook)
}

pub const OPENCODE_PLUGIN_JS: &str = r##"// Coucou hook plugin for OpenCode — generated by Coucou.app
// Forwards every event to the Coucou island (fire-and-forget, never blocks).
import { spawn } from 'node:child_process';

const HOOK = '__HOOK__';
const IS_WINDOWS = process.platform === 'win32';

const EVENT_MAP = {
  'session.created': 'SessionStart',
  'session.idle': 'Stop',
  'session.error': 'StopFailure',
  'session.deleted': 'SessionEnd',
  'permission.asked': 'Notification',
};

function forward(hook_event_name, payload) {
  const body = JSON.stringify({
    hook_event_name,
    coucou_agent: 'opencode',
    ...payload,
  }) + '\n';

  const child = IS_WINDOWS
    ? spawn(HOOK, ['--agent', 'opencode', hook_event_name],
            { stdio: ['pipe', 'ignore', 'ignore'], detached: true })
    : spawn('/bin/sh', [HOOK, '--agent', 'opencode', hook_event_name],
            { stdio: ['pipe', 'ignore', 'ignore'], detached: true });

  child.on('error', () => {});
  child.stdin.on('error', () => {});
  child.stdin.write(body);
  child.stdin.end();
  child.unref();
}

export const CoucouPlugin = async (ctx) => {
  const cwd = ctx?.directory || ctx?.worktree || '';
  const base = (sessionId) => ({ session_id: sessionId || '', cwd });

  return {
    event: async ({ event }) => {
      const hook_event_name = EVENT_MAP[event.type];
      if (!hook_event_name) return;
      const props = event.properties || {};

      if (event.type === 'permission.asked') {
        const tool = props.tool || props.permission || 'a tool';
        forward('Notification', { ...base(event.sessionID), message: `Allow ${tool}?` });
        return;
      }

      if (event.type === 'session.diff' && Array.isArray(props.diff)) {
        for (const file of props.diff) {
          forward('PostToolUse', {
            ...base(event.sessionID),
            tool_name: 'Edit',
            tool_input: { file_path: file.file || file.path || '', diff: file.patch || '' },
          });
        }
        return;
      }

      const payload = base(event.sessionID || props.sessionID || props.session_id);
      if (typeof props.tool === 'string') payload.tool_name = props.tool;
      if (props.input != null) payload.tool_input = props.input;
      forward(hook_event_name, payload);
    },

    'tool.execute.before': async (input) => {
      forward('PreToolUse', {
        ...base(input.sessionID || input.session_id),
        tool_name: typeof input.tool === 'string' ? input.tool : '',
        tool_input: input.input ?? null,
      });
    },

    'tool.execute.after': async (input) => {
      forward('PostToolUse', {
        ...base(input.sessionID || input.session_id),
        tool_name: typeof input.tool === 'string' ? input.tool : '',
      });
    },
  };
};
"##;

fn read_text(path: &Path) -> Result<Option<String>, String> {
    match std::fs::read(path) {
        Ok(bytes) => Ok(Some(String::from_utf8_lossy(&bytes).to_string())),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(err) => Err(format!("Can't read {}: {err}", path.display())),
    }
}

pub fn opencode_status() -> AgentStatus {
    let path = opencode_plugin_path();
    let installed = std::fs::read(&path)
        .map(|b| is_ours(&String::from_utf8_lossy(&b)))
        .unwrap_or(false);
    AgentStatus { installed, path: path.to_string_lossy().to_string() }
}

pub fn opencode_preview(install: bool) -> Result<AgentPreview, String> {
    let path = opencode_plugin_path();
    let current = read_text(&path)?.unwrap_or_default();

    if !install && !is_ours(&current) {
        return Err("No Coucou OpenCode plugin to remove.".into());
    }

    let next = if install {
        opencode_plugin_source(&crate::settings::hook_exe_path().to_string_lossy())
    } else {
        String::new()
    };

    Ok(AgentPreview {
        diff: hooks::unified_diff(&current, &next),
        backup: hooks::backup_path_for(&path, &hooks::stamp()).to_string_lossy().to_string(),
        path: path.to_string_lossy().to_string(),
        fingerprint: hooks::fingerprint(current.as_bytes()),
    })
}

/// Writes the plugin (or deletes it), after a dated backup and only if the file
/// still matches what the user reviewed.
pub fn opencode_write(install: bool, fingerprint: &str) -> Result<String, String> {
    let path = opencode_plugin_path();
    let current = read_text(&path)?.unwrap_or_default();

    if hooks::fingerprint(current.as_bytes()) != fingerprint {
        return Err(format!(
            "{} changed since the preview. Nothing was written — review the new diff.",
            path.display()
        ));
    }

    let mut backup = String::new();
    if path.exists() {
        let b = hooks::backup_path_for(&path, &hooks::stamp());
        std::fs::copy(&path, &b).map_err(|e| format!("backup failed: {e}"))?;
        backup = b.to_string_lossy().to_string();
    }

    if !install {
        // Refuse to delete a file we did not write.
        if path.exists() && !is_ours(&current) {
            return Err(format!(
                "{} was not generated by Coucou — not deleting it.",
                path.display()
            ));
        }
        std::fs::remove_file(&path).map_err(|e| format!("delete failed: {e}"))?;
        return Ok(backup);
    }

    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    }
    let text = opencode_plugin_source(&crate::settings::hook_exe_path().to_string_lossy());
    let temp = path.with_extension(format!("js.coucou-{}", std::process::id()));
    hooks::write_like(&temp, &path, text.as_bytes()).map_err(|e| format!("write failed: {e}"))?;
    std::fs::rename(&temp, &path).map_err(|e| format!("write failed: {e}"))?;
    Ok(backup)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_plugin_is_windows_capable_and_keeps_its_identity_markers() {
        let js = opencode_plugin_source("C:/Users/x/AppData/Local/coucou/bin/coucou-hook.exe");
        // opencode_plugin_installed() looks for these; losing one breaks uninstall.
        assert!(js.contains(OPENCODE_MARKER));
        assert!(js.contains("--agent', 'opencode'"));
        assert!(js.contains("coucou_agent: 'opencode'"));
        // Windows support.
        assert!(js.contains("process.platform === 'win32'"));
        assert!(js.contains("coucou-hook.exe"));
        // Parity with macOS.
        assert!(js.contains("ctx?.directory"));
        assert!(js.contains("session.diff"));
        // The placeholder must be gone.
        assert!(!js.contains("__HOOK__"));
        // Backslashes in the path must be escaped for the JS string literal.
        let win = opencode_plugin_source(r"C:\Users\x\coucou-hook.exe");
        assert!(win.contains(r"C:\\Users\\x\\coucou-hook.exe"), "{win}");
    }

    #[test]
    fn a_foreign_plugin_file_is_never_deleted() {
        // Anything not generated by Coucou is left alone on uninstall.
        assert!(is_ours("// Coucou hook plugin for OpenCode — generated by Coucou.app"));
        assert!(!is_ours("// my own plugin"));
        assert!(!is_ours(""));
    }

    #[test]
    fn the_backup_name_is_unique_per_second() {
        let p = PathBuf::from("/tmp/opencode/coucou.js");
        let a = hooks::backup_path_for(&p, "20261007-120000");
        let b = hooks::backup_path_for(&p, "20261007-120001");
        assert_ne!(a, b);
        assert!(a.to_string_lossy().contains("20261007-120000"));
    }
}
