// OpenCode plugin and Hermes shell-hook installation.
//
// Kept out of hooks.rs on purpose: that file is entirely about Claude Code's
// settings.json, and the merge rules here are different (a JS file we own outright,
// and a YAML block we own between markers). Same preview/backup/confirm discipline.

use std::path::{Path, PathBuf};

use serde::Serialize;

use crate::{hooks, platform};

/// Identifies a file Coucou generated, and is checked before deleting anything.
pub const OPENCODE_MARKER: &str = "generated by Coucou";

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentStatus {
    pub installed: bool,
    pub path: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentPreview {
    pub diff: String,
    pub backup: String,
    pub path: String,
    /// The bytes this diff was computed from; handed back to `write` so we only
    /// ever apply what the user actually looked at.
    pub fingerprint: String,
}

pub fn opencode_plugin_path() -> PathBuf {
    // XDG-style on every platform, which is what OpenCode itself uses — that is
    // why OpenCode works on Windows and Amp does not.
    platform::home_dir().join(".config/opencode/plugins/coucou.js")
}

fn is_ours(text: &str) -> bool {
    text.contains(OPENCODE_MARKER)
}

/// The generated plugin, with the relay path substituted in.
///
/// ponytail: the same JavaScript exists as a Swift string literal in HookServer.swift
/// for the macOS app. Two copies because the two apps are separate binaries; both
/// sides assert the same tokens in their own test, so a drift shows up as a failure
/// rather than as a silently broken agent.
pub fn opencode_plugin_source(hook_exe: &str) -> String {
    // Backslashes would start an escape inside the JS single-quoted literal.
    let hook = hook_exe.replace('\\', "\\\\").replace('\'', "\\'");
    OPENCODE_PLUGIN_JS.replace("__HOOK__", &hook)
}

pub const OPENCODE_PLUGIN_JS: &str = r##"// Coucou hook plugin for OpenCode — generated by Coucou.app
// Forwards every event to the Coucou island (fire-and-forget, never blocks).
import { spawn } from 'node:child_process';

const HOOK = '__HOOK__';
const IS_WINDOWS = process.platform === 'win32';

const EVENT_MAP = {
  'session.created': 'SessionStart',
  'session.idle': 'Stop',
  'session.error': 'StopFailure',
  'session.deleted': 'SessionEnd',
  // session.diff MUST have an entry here: the handler below starts with
  // `if (!hook_event_name) return;`, so a type missing from this map is
  // swallowed before any branch runs. This key keeps the event past that guard;
  // the specific `event.type === 'session.diff'` branch then handles it (one
  // forward per changed file) and returns, so the generic path never sees it.
  'session.diff': 'PostToolUse',
  'permission.asked': 'Notification',
};

function forward(hook_event_name, payload) {
  const body = JSON.stringify({
    hook_event_name,
    coucou_agent: 'opencode',
    ...payload,
  }) + '\n';

  const child = IS_WINDOWS
    ? spawn(HOOK, ['--agent', 'opencode', hook_event_name],
            { stdio: ['pipe', 'ignore', 'ignore'], detached: true })
    : spawn('/bin/sh', [HOOK, '--agent', 'opencode', hook_event_name],
            { stdio: ['pipe', 'ignore', 'ignore'], detached: true });

  child.on('error', () => {});
  child.stdin.on('error', () => {});
  child.stdin.write(body);
  child.stdin.end();
  child.unref();
}

export const CoucouPlugin = async (ctx) => {
  const cwd = ctx?.directory || ctx?.worktree || '';
  const base = (sessionId) => ({ session_id: sessionId || '', cwd });

  return {
    event: async ({ event }) => {
      const hook_event_name = EVENT_MAP[event.type];
      if (!hook_event_name) return;
      const props = event.properties || {};

      if (event.type === 'permission.asked') {
        const tool = props.tool || props.permission || 'a tool';
        forward('Notification', { ...base(event.sessionID), message: `Allow ${tool}?` });
        return;
      }

      if (event.type === 'session.diff' && Array.isArray(props.diff)) {
        for (const file of props.diff) {
          forward('PostToolUse', {
            ...base(event.sessionID),
            tool_name: 'Edit',
            tool_input: { file_path: file.file || file.path || '', diff: file.patch || '' },
          });
        }
        return;
      }

      const payload = base(event.sessionID || props.sessionID || props.session_id);
      if (typeof props.tool === 'string') payload.tool_name = props.tool;
      if (props.input != null) payload.tool_input = props.input;
      forward(hook_event_name, payload);
    },

    'tool.execute.before': async (input) => {
      forward('PreToolUse', {
        ...base(input.sessionID || input.session_id),
        tool_name: typeof input.tool === 'string' ? input.tool : '',
        tool_input: input.input ?? null,
      });
    },

    'tool.execute.after': async (input) => {
      forward('PostToolUse', {
        ...base(input.sessionID || input.session_id),
        tool_name: typeof input.tool === 'string' ? input.tool : '',
      });
    },
  };
};
"##;

fn read_text(path: &Path) -> Result<Option<String>, String> {
    match std::fs::read(path) {
        Ok(bytes) => Ok(Some(String::from_utf8_lossy(&bytes).to_string())),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(err) => Err(format!("Can't read {}: {err}", path.display())),
    }
}

pub fn opencode_status() -> AgentStatus {
    let path = opencode_plugin_path();
    let installed = std::fs::read(&path)
        .map(|b| is_ours(&String::from_utf8_lossy(&b)))
        .unwrap_or(false);
    AgentStatus { installed, path: path.to_string_lossy().to_string() }
}

pub fn opencode_preview(install: bool) -> Result<AgentPreview, String> {
    let path = opencode_plugin_path();
    let current = read_text(&path)?.unwrap_or_default();

    if !install && !is_ours(&current) {
        return Err("No Coucou OpenCode plugin to remove.".into());
    }

    let next = if install {
        opencode_plugin_source(&crate::settings::hook_exe_path().to_string_lossy())
    } else {
        String::new()
    };

    Ok(AgentPreview {
        diff: hooks::unified_diff(&current, &next),
        backup: hooks::backup_path_for(&path, &hooks::stamp()).to_string_lossy().to_string(),
        path: path.to_string_lossy().to_string(),
        fingerprint: hooks::fingerprint(current.as_bytes()),
    })
}

/// Writes the plugin (or deletes it), after a dated backup and only if the file
/// still matches what the user reviewed.
pub fn opencode_write(install: bool, fingerprint: &str) -> Result<String, String> {
    let path = opencode_plugin_path();
    let current = read_text(&path)?.unwrap_or_default();

    if hooks::fingerprint(current.as_bytes()) != fingerprint {
        return Err(format!(
            "{} changed since the preview. Nothing was written — review the new diff.",
            path.display()
        ));
    }

    // Refuse to delete a file we did not write, before taking the backup: a
    // refused uninstall must leave no stray .bak beside a file we left alone.
    if !install && path.exists() && !is_ours(&current) {
        return Err(format!(
            "{} was not generated by Coucou — not deleting it.",
            path.display()
        ));
    }

    let mut backup = String::new();
    if path.exists() {
        let b = hooks::backup_path_for(&path, &hooks::stamp());
        std::fs::copy(&path, &b).map_err(|e| format!("backup failed: {e}"))?;
        backup = b.to_string_lossy().to_string();
    }

    if !install {
        std::fs::remove_file(&path).map_err(|e| format!("delete failed: {e}"))?;
        return Ok(backup);
    }

    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    }
    let text = opencode_plugin_source(&crate::settings::hook_exe_path().to_string_lossy());
    let temp = path.with_extension(format!("js.coucou-{}", std::process::id()));
    if let Err(err) = hooks::write_like(&temp, &path, text.as_bytes()) {
        let _ = std::fs::remove_file(&temp);
        return Err(format!("write failed: {err}"));
    }
    if let Err(err) = std::fs::rename(&temp, &path) {
        let _ = std::fs::remove_file(&temp);
        return Err(format!("write failed: {err}"));
    }
    Ok(backup)
}

// ── Hermes ────────────────────────────────────────────────────────────────────

pub const HERMES_BEGIN: &str = "# coucou:begin";
pub const HERMES_END: &str = "# coucou:end";

/// Hermes fires `pre_tool_call` for every tool, so the gate is scoped to the tools
/// that change something. Hermes truncates `timeout` at 300 s.
pub const HERMES_GATE_MATCHER: &str = "terminal|write_file|patch";

/// Hermes' home directory, resolved the way Hermes resolves it.
///
/// `$HERMES_HOME` wins. Otherwise Windows uses `%LOCALAPPDATA%\hermes` — **not**
/// `~/.hermes`, which is the POSIX default and does not exist on a Windows install.
/// Getting this wrong is silent: the installer reports success, and Hermes never
/// loads the hook. Verified with `hermes config path`, which prints
/// `C:\Users\<user>\AppData\Local\hermes\config.yaml` on this machine.
pub fn hermes_home() -> PathBuf {
    if let Some(home) = std::env::var_os("HERMES_HOME") {
        if !home.is_empty() {
            return PathBuf::from(home);
        }
    }
    #[cfg(windows)]
    {
        if let Some(local) = std::env::var_os("LOCALAPPDATA") {
            if !local.is_empty() {
                return PathBuf::from(local).join("hermes");
            }
        }
    }
    platform::home_dir().join(".hermes")
}

pub fn hermes_config_path() -> PathBuf {
    hermes_home().join("config.yaml")
}

/// The consent allowlist Hermes keeps beside its config. Coucou does not write it —
/// the user approves each hook — but the docs and the manual test need the path.
pub fn hermes_allowlist_path() -> PathBuf {
    hermes_home().join("shell-hooks-allowlist.json")
}

/// The marker-delimited block Coucou owns inside ~/.hermes/config.yaml.
///
/// ponytail: plain text between markers, not a YAML round-trip — the workspace has
/// no YAML crate and reformatting a user's config would be worse than the problem.
/// Ceiling: a user who already owns a top-level `hooks:` key is refused rather than
/// merged. Upgrade path: adopt a YAML crate if that refusal starts firing often.
pub fn hermes_config_block(hook_command: &str) -> String {
    format!(
        "{HERMES_BEGIN} — managed by Coucou. Edits inside these markers are overwritten.\n\
         hooks:\n\
         \x20 pre_llm_call:\n\
         \x20   - command: '{hook_command} pre_llm_call'\n\
         \x20     timeout: 10\n\
         \x20 pre_tool_call:\n\
         \x20   - matcher: \"{HERMES_GATE_MATCHER}\"\n\
         \x20     command: '{hook_command} pre_tool_call'\n\
         \x20     timeout: 130\n\
         \x20 post_tool_call:\n\
         \x20   - command: '{hook_command} post_tool_call'\n\
         \x20     timeout: 10\n\
         \x20 on_session_start:\n\
         \x20   - command: '{hook_command} on_session_start'\n\
         \x20     timeout: 10\n\
         \x20 on_session_end:\n\
         \x20   - command: '{hook_command} on_session_end'\n\
         \x20     timeout: 10\n\
         \x20 subagent_start:\n\
         \x20   - command: '{hook_command} subagent_start'\n\
         \x20     timeout: 10\n\
         \x20 subagent_stop:\n\
         \x20   - command: '{hook_command} subagent_stop'\n\
         \x20     timeout: 10\n\
         {HERMES_END}"
    )
}

/// `existing` with Coucou's block installed (`hook_command` = Some) or removed (None).
pub fn merge_hermes_config(
    existing: &str,
    hook_command: Option<&str>,
) -> Result<String, String> {
    let had_ours = existing.contains(HERMES_BEGIN);

    // Strip any previous block of ours, so install is idempotent and uninstall
    // leaves the file exactly as we found it.
    let mut body = String::new();
    if had_ours {
        let mut inside = false;
        for line in existing.lines() {
            if line.starts_with(HERMES_BEGIN) { inside = true; continue; }
            if line.starts_with(HERMES_END) { inside = false; continue; }
            if !inside {
                body.push_str(line);
                body.push('\n');
            }
        }
    } else {
        body = existing.to_string();
    }

    let Some(cmd) = hook_command else {
        // Nothing of ours to remove: hand the file back untouched rather than
        // normalising whitespace in a config we do not own.
        if !had_ours {
            return Ok(body);
        }
        while body.contains("\n\n\n") {
            body = body.replace("\n\n\n", "\n\n");
        }
        // Install put one blank line between the user's content and our block;
        // uninstall takes that blank back out, so the file we hand back is byte
        // for byte the one we were given.
        if body.ends_with("\n\n") {
            body.pop();
        }
        return Ok(body);
    };

    // Refuse a foreign hooks: key — but only when we have not already taken it over.
    if !had_ours {
        let has_foreign = body.lines().any(|l| {
            let t = l.trim_end();
            t == "hooks:" && !l.starts_with(' ') && !l.starts_with('\t')
        });
        if has_foreign {
            return Err(format!(
                "~/.hermes/config.yaml already has a top-level `hooks:` key that Coucou does \
                 not manage. Nothing was written — paste this block into it yourself:\n\n{}",
                hermes_config_block(cmd)
            ));
        }
    }

    if !body.is_empty() && !body.ends_with('\n') {
        body.push('\n');
    }
    if !body.is_empty() && !body.ends_with("\n\n") {
        body.push('\n');
    }
    body.push_str(&hermes_config_block(cmd));
    body.push('\n');
    Ok(body)
}

pub fn hermes_status() -> AgentStatus {
    let path = hermes_config_path();
    let installed = std::fs::read(&path)
        .map(|b| String::from_utf8_lossy(&b).contains(HERMES_BEGIN))
        .unwrap_or(false);
    AgentStatus { installed, path: path.to_string_lossy().to_string() }
}

pub fn hermes_preview(install: bool) -> Result<AgentPreview, String> {
    let path = hermes_config_path();
    let current = read_text(&path)?.unwrap_or_default();

    if !install && !current.contains(HERMES_BEGIN) {
        return Err("No Coucou Hermes hooks to remove.".into());
    }

    let hook_command = crate::settings::hook_exe_path().to_string_lossy().to_string();
    let cmd = format!("\"{}\" --agent hermes", hook_command);
    let next = merge_hermes_config(&current, install.then_some(cmd.as_str()))?;

    Ok(AgentPreview {
        diff: hooks::unified_diff(&current, &next),
        backup: hooks::backup_path_for(&path, &hooks::stamp()).to_string_lossy().to_string(),
        path: path.to_string_lossy().to_string(),
        fingerprint: hooks::fingerprint(current.as_bytes()),
    })
}

/// Writes the block (or removes it), after a dated backup and only if the file
/// still matches what the user reviewed.
pub fn hermes_write(install: bool, fingerprint: &str) -> Result<String, String> {
    let path = hermes_config_path();
    let current = read_text(&path)?.unwrap_or_default();

    if hooks::fingerprint(current.as_bytes()) != fingerprint {
        return Err(format!(
            "{} changed since the preview. Nothing was written — review the new diff.",
            path.display()
        ));
    }

    // Nothing of ours to remove: refuse before the backup, as OpenCode does, so a
    // declined uninstall leaves no stray .bak beside a config we do not own.
    if !install && !current.contains(HERMES_BEGIN) {
        return Err("No Coucou Hermes hooks to remove.".into());
    }

    let hook_command = crate::settings::hook_exe_path().to_string_lossy().to_string();
    let cmd = format!("\"{}\" --agent hermes", hook_command);
    // `merge_hermes_config` refuses a foreign `hooks:` key before we take a
    // backup, so nothing on disk is touched when the user's YAML is not ours.
    let next = merge_hermes_config(&current, install.then_some(cmd.as_str()))?;

    let mut backup = String::new();
    if path.exists() {
        let b = hooks::backup_path_for(&path, &hooks::stamp());
        std::fs::copy(&path, &b).map_err(|e| format!("backup failed: {e}"))?;
        backup = b.to_string_lossy().to_string();
    }

    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    }
    let temp = path.with_extension(format!("yaml.coucou-{}", std::process::id()));
    if let Err(err) = hooks::write_like(&temp, &path, next.as_bytes()) {
        let _ = std::fs::remove_file(&temp);
        return Err(format!("write failed: {err}"));
    }
    if let Err(err) = std::fs::rename(&temp, &path) {
        let _ = std::fs::remove_file(&temp);
        return Err(format!("write failed: {err}"));
    }
    Ok(backup)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_plugin_is_windows_capable_and_keeps_its_identity_markers() {
        let js = opencode_plugin_source("C:/Users/x/AppData/Local/coucou/bin/coucou-hook.exe");
        // opencode_plugin_installed() looks for these; losing one breaks uninstall.
        assert!(js.contains(OPENCODE_MARKER));
        assert!(js.contains("--agent', 'opencode'"));
        assert!(js.contains("coucou_agent: 'opencode'"));
        // Windows support.
        assert!(js.contains("process.platform === 'win32'"));
        assert!(js.contains("coucou-hook.exe"));
        // Parity with macOS.
        assert!(js.contains("ctx?.directory"));
        // `session.diff` is covered behaviourally by
        // `the_session_diff_branch_is_reachable` below, not by a substring check
        // here — the literal string is present in a dead branch even when the
        // map entry is missing, which is exactly the bug that test guards.
        // The placeholder must be gone.
        assert!(!js.contains("__HOOK__"));
        // Backslashes in the path must be escaped for the JS string literal.
        let win = opencode_plugin_source(r"C:\Users\x\coucou-hook.exe");
        assert!(win.contains(r"C:\\Users\\x\\coucou-hook.exe"), "{win}");
    }

    #[test]
    fn the_session_diff_branch_is_reachable() {
        // The handler opens with `if (!hook_event_name) return;`, so any event
        // type missing from EVENT_MAP is dropped before a branch can run. The
        // per-file diff forwarding only executes if `session.diff` is in the map
        // *and* its branch sits downstream of the lookup. Assert both, so
        // deleting the map entry (or the branch) fails here instead of silently
        // forwarding nothing.
        let js = opencode_plugin_source("C:/x/coucou-hook.exe");

        // 1. The map literal must carry a `session.diff` key.
        let map_start = js.find("const EVENT_MAP = {").expect("EVENT_MAP literal");
        let map_end = js[map_start..].find("};").expect("EVENT_MAP terminator") + map_start;
        let map = &js[map_start..map_end];
        assert!(
            map.contains("'session.diff':"),
            "EVENT_MAP must key session.diff or the early return swallows it:\n{map}"
        );

        // 2. The gating lookup must come before the session.diff branch, so the
        //    branch is genuinely downstream of the guard rather than unreachable.
        //    Match the whole branch condition, not just the event name — the
        //    name alone also appears in the EVENT_MAP comment above.
        let lookup = js.find("EVENT_MAP[event.type]").expect("EVENT_MAP lookup");
        let branch = js
            .find("if (event.type === 'session.diff' && Array.isArray(props.diff))")
            .expect("session.diff branch");
        assert!(
            lookup < branch,
            "the session.diff branch must follow the EVENT_MAP lookup that gates it"
        );
    }

    #[test]
    fn a_foreign_plugin_file_is_never_deleted() {
        // Anything not generated by Coucou is left alone on uninstall.
        assert!(is_ours("// Coucou hook plugin for OpenCode — generated by Coucou.app"));
        assert!(!is_ours("// my own plugin"));
        assert!(!is_ours(""));
    }

    #[test]
    fn the_backup_name_is_unique_per_second() {
        let p = PathBuf::from("/tmp/opencode/coucou.js");
        let a = hooks::backup_path_for(&p, "20261007-120000");
        let b = hooks::backup_path_for(&p, "20261007-120001");
        assert_ne!(a, b);
        assert!(a.to_string_lossy().contains("20261007-120000"));
    }

    #[test]
    fn the_hermes_block_is_marker_scoped_and_never_fail_closed() {
        let block = hermes_config_block(r#""C:/x/coucou-hook.exe" --agent hermes"#);
        assert!(block.starts_with(HERMES_BEGIN));
        assert!(block.ends_with(HERMES_END));
        for event in ["pre_llm_call", "pre_tool_call", "post_tool_call",
                      "on_session_start", "on_session_end", "subagent_start", "subagent_stop"] {
            assert!(block.contains(&format!("{event}:")), "the block must declare {event}");
        }
        // Only pre_tool_call may carry a matcher or a long timeout: Hermes honours a
        // block directive on that event alone (shell_hooks.py: _BLOCKING_EVENTS).
        assert_eq!(block.matches("matcher:").count(), 1, "exactly one matcher, on pre_tool_call");
        assert_eq!(block.matches("timeout: 130").count(), 1, "only the gate waits");
        // A closed Coucou must never block Hermes: fail-open is the contract.
        assert!(!block.contains("fail_closed"));
        // The command holds double quotes, so the YAML scalar must be single-quoted.
        assert!(block.contains("command: '"));
        assert!(!block.contains("command: \""));
    }

    #[test]
    fn the_hermes_config_lives_where_hermes_says_it_does() {
        // Hermes resolves its home as: $HERMES_HOME, else %LOCALAPPDATA%\hermes on
        // Windows, else ~/.hermes. Writing anywhere else means the installer reports
        // success and Hermes never loads the hook. Verified against the real install:
        //   $ hermes config path
        //   C:\Users\Stanley\AppData\Local\hermes\config.yaml
        std::env::remove_var("HERMES_HOME");
        let p = hermes_config_path();

        if cfg!(windows) {
            let local = std::env::var("LOCALAPPDATA").expect("LOCALAPPDATA is set on Windows");
            let want = PathBuf::from(local).join("hermes").join("config.yaml");
            assert_eq!(p, want, "must match `hermes config path`");
            // The old bug: a `.hermes` segment under the user profile.
            assert!(
                !p.to_string_lossy().contains(".hermes"),
                "the Windows home has no .hermes segment — got {p:?}"
            );
        } else {
            assert!(p.ends_with(".hermes/config.yaml"), "got {p:?}");
        }

        // $HERMES_HOME wins, and the allowlist sits beside the config.
        std::env::set_var("HERMES_HOME", r"C:\tmp\hermes-test");
        assert_eq!(hermes_config_path(), PathBuf::from(r"C:\tmp\hermes-test").join("config.yaml"));
        assert_eq!(hermes_allowlist_path(), PathBuf::from(r"C:\tmp\hermes-test").join("shell-hooks-allowlist.json"));
        std::env::remove_var("HERMES_HOME");
    }

    #[test]
    fn merging_preserves_the_users_file_and_is_idempotent() {
        let cmd = r#""C:/x/coucou-hook.exe" --agent hermes"#;
        let original = "model: opus\nprofile: default\n";

        let once = merge_hermes_config(original, Some(cmd)).unwrap();
        assert!(once.starts_with("model: opus\nprofile: default\n"));
        assert!(once.contains("pre_tool_call:"));

        let twice = merge_hermes_config(&once, Some(cmd)).unwrap();
        assert_eq!(
            twice.matches(HERMES_BEGIN).count(),
            once.matches(HERMES_BEGIN).count(),
            "re-installing must replace the block, not stack a second one"
        );

        assert_eq!(merge_hermes_config(&once, None).unwrap(), original);
        assert!(merge_hermes_config("", Some(cmd)).unwrap().contains("pre_tool_call:"));
    }

    #[test]
    fn a_foreign_hooks_key_is_refused_not_merged() {
        let cmd = r#""C:/x/coucou-hook.exe" --agent hermes"#;
        let foreign = "model: opus\nhooks:\n  pre_llm_call:\n    - command: mine.sh\n";
        let err = merge_hermes_config(foreign, Some(cmd)).unwrap_err();
        assert!(err.contains("hooks:"), "{err}");
        assert!(err.contains("paste"), "{err}");
    }
}
